/* Generated by tools/mine-openings.mjs (npm run openings) - do not edit by hand.
 *
 * Every opening from which each Mine A Shape! picture in js/mineshapes.js can be solved
 * without a single guess, as [column, row], with a fingerprint of the rows they were worked
 * out from and the picture's difficulty profile - how many stalls need two numbers, the mine
 * count, or deeper reasoning (tools/mine-difficulty.mjs). createShapeGame picks an opening at
 * random; nothing here reaches the player. tests/mineshapes fails if a fingerprint no longer
 * matches its picture: re-run the tool.
 */
export const MINE_OPENINGS = {
    "heart": {
        fingerprint: '8d31a456',
        difficulty: { simpleRounds: 17, pair: 2, count: 0, deeper: 3, sampled: 2 },
        openings: [
            [5,6], [6,6],
        ],
    },
    "Mine Nonsense V1": {
        fingerprint: 'e4a2129d',
        difficulty: { simpleRounds: 72, pair: 10, count: 1, deeper: 3, sampled: 5 },
        openings: [
            [10,10], [10,11], [10,12], [8,13], [9,13], [10,13], [11,13], [12,13], [18,13], [19,13],
            [20,13], [9,14], [10,14], [11,14], [19,14], [20,14], [9,15], [10,15], [11,15], [19,15],
            [20,15], [1,19], [2,19], [3,19], [4,19], [5,19], [6,19], [7,19], [8,19], [9,19],
            [10,19], [11,19], [12,19], [13,19], [14,19], [15,19], [16,19], [17,19], [18,19], [19,19],
            [20,19], [1,20], [2,20], [3,20], [4,20], [5,20], [6,20], [7,20], [8,20], [9,20],
            [10,20], [11,20], [12,20], [13,20], [14,20], [15,20], [16,20], [17,20], [18,20], [19,20],
            [20,20],
        ],
    },
    "bear": {
        fingerprint: 'eafddeba',
        difficulty: { simpleRounds: 15, pair: 0, count: 0, deeper: 0, sampled: 5 },
        openings: [
            [6,7], [10,7], [11,7], [15,7], [6,8], [10,8], [11,8], [15,8], [6,9], [10,9],
            [11,9], [15,9], [6,10], [7,10], [14,10], [15,10], [6,11], [7,11], [14,11], [15,11],
            [6,12], [7,12], [14,12], [15,12],
        ],
    },
};
