/* Generated by tools/mine-openings.mjs (npm run openings) - do not edit by hand.
 *
 * Every opening from which each Mine A Shape! picture in js/mineshapes.js can be solved
 * without a single guess, as [column, row], with a fingerprint of the rows they were worked
 * out from. createShapeGame picks one at random. tests/mineshapes fails if a fingerprint no
 * longer matches its picture: re-run the tool.
 */
export const MINE_OPENINGS = {
    "heart": {
        fingerprint: '8d31a456',
        openings: [
            [5,6], [6,6],
        ],
    },
    "Mine Nonsense V1": {
        fingerprint: 'e4a2129d',
        openings: [
            [10,10], [10,11], [10,12], [8,13], [9,13], [10,13], [11,13], [12,13], [18,13], [19,13],
            [20,13], [9,14], [10,14], [11,14], [19,14], [20,14], [9,15], [10,15], [11,15], [19,15],
            [20,15], [1,19], [2,19], [3,19], [4,19], [5,19], [6,19], [7,19], [8,19], [9,19],
            [10,19], [11,19], [12,19], [13,19], [14,19], [15,19], [16,19], [17,19], [18,19], [19,19],
            [20,19], [1,20], [2,20], [3,20], [4,20], [5,20], [6,20], [7,20], [8,20], [9,20],
            [10,20], [11,20], [12,20], [13,20], [14,20], [15,20], [16,20], [17,20], [18,20], [19,20],
            [20,20],
        ],
    },
};
