/* Builds js/tnoalbedos.js: one measured visual albedo, with its absolute magnitude, for
 * every trans-Neptunian object in Johnston's compilation of TNO and Centaur diameters,
 * albedos and densities (https://www.johnstonsarchive.net/astro/tnodiam.html; archived
 * at NASA PDS, doi:10.26033/y5sn-4t02).
 *
 * Dev-only, like tools/mine-openings.mjs: never shipped. It reads a saved copy of the
 * page so that re-running it does not touch the site:
 *
 *     node tools/tno-albedos.mjs path/to/tnodiam.html "20 June 2026"
 *
 * The second argument is the page's "last modified" date, recorded in the output.
 *
 * The page lists every published measurement, in date order. One is chosen per object:
 *   - only measured albedos: none assumed (A), derived ([...]) or limits (< >);
 *   - visual-band albedos only (V, or geometric *), since H is visual;
 *   - the most direct method: occultation, then imaging or eclipses, then thermal,
 *     then binary orbit (which assumes a density);
 *   - among equals, the latest.
 * Only TNOs are kept: no centaurs, satellites or Neptune trojans, which are not the
 * population the Rubin filter looks at.
 */
import { readFileSync, writeFileSync } from 'node:fs';

const [, , htmlPath, modified] = process.argv;
if (!htmlPath || !modified) {
    console.error('usage: node tools/tno-albedos.mjs <saved tnodiam.html> "<last modified date>"');
    process.exit(1);
}

const METHOD_RANK = { O: 4, I: 3, E: 3, T: 2, H: 2, Y: 1 };
const EXCLUDED_TYPES = /^(CEN|SAT|NL4)/;

const text = (cell) => cell
    .replace(/<[^>]*>/g, ' ')
    .replace(/&plusmn;/g, '±')
    .replace(/&nbsp;/g, ' ')
    .replace(/&lt;/g, '<')
    .replace(/&gt;/g, '>')
    .replace(/&amp;/g, '&')
    .replace(/\s+/g, ' ')
    .trim();

const firstNumber = (value) => {
    const match = value.match(/^-?\d+(\.\d+)?/);
    return match ? Number(match[0]) : null;
};

/* A usable albedo: measured, visual, a plain number. */
function measuredAlbedo(cell) {
    if (!cell || /^[A[<>]/.test(cell)) return null;
    const band = cell.match(/\s([VRB*])$/);
    if (band && !['V', '*'].includes(band[1])) return null;
    const value = firstNumber(cell);
    return value !== null && value > 0 && value <= 1.5 ? value : null;
}

const html = readFileSync(htmlPath, 'utf8');
const rows = [...html.matchAll(/<tr>([\s\S]*?)<\/tr>/g)].map((m) => [...m[1].matchAll(/<td[^>]*>([\s\S]*?)<\/td>/g)].map((c) => text(c[1])));

const objects = [];
let current = null;
for (const cells of rows) {
    let measurement;
    if (cells.length === 12) {
        const [name, designation, type, jplH] = cells;
        current = { name, designation, type, jplH: firstNumber(jplH), measurements: [] };
        objects.push(current);
        measurement = cells.slice(4);
    } else if (cells.length === 8 && current) {
        measurement = cells;
    } else continue;
    const [hv, , , , albedo, , method, source] = measurement;
    current.measurements.push({ hv: firstNumber(hv), albedo: measuredAlbedo(albedo), method: method.split(/[\s(*]/)[0], source });
}

const chosen = [];
for (const object of objects) {
    if (EXCLUDED_TYPES.test(object.type)) continue;
    let best = null;
    object.measurements.forEach((m, order) => {
        if (m.albedo === null) return;
        const rank = METHOD_RANK[m.method] ?? 0;
        if (!best || rank > best.rank || (rank === best.rank && order > best.order)) best = { ...m, rank, order };
    });
    if (!best) continue;
    const H = best.hv ?? object.jplH;
    if (H === null) continue;
    const label = [object.name, object.designation].filter(Boolean).join(" ");
    chosen.push({ name: label, H, albedo: best.albedo, method: best.method, source: best.source });
}
chosen.sort((a, b) => a.H - b.H);

const header = `/* GENERATED by tools/tno-albedos.mjs - do not edit by hand.
 *
 * Measured visual albedos of trans-Neptunian objects, one per object, from Johnston's
 * compilation of TNO and Centaur diameters, albedos and densities
 * (https://www.johnstonsarchive.net/astro/tnodiam.html, last modified ${modified};
 * archived at NASA PDS, doi:10.26033/y5sn-4t02). See the tool for how one measurement
 * is chosen per object. ${chosen.length} objects.
 *
 * Fields: name, H (visual absolute magnitude used with the albedo), albedo (visual
 * geometric), method (O occultation, I imaging, E eclipses, T thermal, Y binary orbit),
 * source (the compilation's reference code).
 */
`;
const body = `export const TNO_ALBEDOS_MODIFIED = ${JSON.stringify(modified)};\n\nexport const TNO_ALBEDOS = [\n${chosen.map((o) => `    ${JSON.stringify(o)},`).join('\n')}\n];\n`;
writeFileSync(new URL('../js/tnoalbedos.js', import.meta.url), header + body);
console.log(`${objects.length} objects in the table, ${chosen.length} TNOs with a usable albedo -> js/tnoalbedos.js`);
